proposals/debug-id.md

This is a proposal for #19. The idea is to embed globally unique debug or build IDs into source maps and transpiled JavaScript files. This enables a work flow similar to native object files and their debug companions or WASM files (https://github.com/WebAssembly/tool-conventions/issues/133).
[Rendered text](https://github.com/mitsuhiko/source-map-rfc/blob/proposals/debug-id/proposals/debug-id.md)

Added debug id proposal

---

proposals/env.md

Proposal for #2.
I've tried to make this precise and detailed, perhaps at the cost of some brevity, but I was also not 100% sure how detailed and specific to be at times. I am very open to suggested changes, particularly anything that is not clear to potential implementers.
Looking forward to feedback.

 Proposal for encoding source-level environment information

---

PROCESS.md

Now that we have multiple concrete proposals going on (debug IDs, scopes) and some potential proposals (such as standardizing the JS tokens source maps point to), some of us have been thinking about some sort of process to help standardizing these features and to make sure that all the different parties are involved in the discussions.
These stages have been originally written down by @littledan, and I further refined them.
It's based on the main TC39 process, but with some changes to avoid the slowdown that TC39's process sometimes causes. Most importantly, this tries to encourage experimental implementation early to help guiding the proposals design.
I'd love to hear your opinions about this :)

Meta-proposal: stages process for proposals

---

proposals/scopes.md

This PR is intended to kick-off discussion on how to fix the spec to properly support the scenarios pointed out in [here](https://github.com/tc39/source-map-rfc/issues/37#issuecomment-1808110066) and [here](https://github.com/tc39/source-map-rfc/issues/61).
The two large changes are:
1. In addition to the generated scopes, we now also encode the original scope tree for ever `sources` entry. `definition` was changed to point back to the corresponding original scope instead. This fixes the missing outer scope information for inlined function of the current proposal.
2. Bindings are handled as "live ranges" instead: Each original scope specifies which variables/symbols it declares. For each symbol we specify the generated code ranges where this symbol is available and which expression to use …

scopes: Encode original scope trees and use live ranges for bindings

---

proposals/scopes.md

We don't need to include the number of variables/bindings in the encoded scope information: variables/bindings are added at the end of each "Start Scope" item and so the sourcemap consumer can simply decode variables/bindings until it reaches the end of that item.
So we can make the encoded scopes a little smaller by removing the number of variables/bindings. (The only possible downside is that we lose the potential to extend the current format in a backward compatible way by adding information to the end of a "Start Scope" item)

Remove hasBindings and bindings count from scopes encoding

---

proposals/scopes.md

We need to specify whether a `GeneratedRange` corresponds to a scope in the generated source.
This PR is on top of #68.

Add GeneratedRange.isScope flag

---

proposals/scopes.md

At the last meeting we decided to make the offsets into the names array absolute for now until we have decided how to deal with #70 .
@jridgewell I also wanted to add you as a reviewer but for some reason Github won't let me.

Scopes: Make the offsets into the names array absolute

---

source-map.bs

This was originally opened at https://github.com/tc39/source-map-spec/pull/30
I am currently being hand-wavy about CSS, only saying "it should be similar to JS". I can propose the adjusted algorithm in a followup, but given that technically source maps are not language-specific we might also just say "other text languages should be like JS, adapted to their own comments syntax".
---
This patch explicitly defines how to extract such comments from JavaScript, CSS and WebAssembly sources.
It defines multiple ways to do so: either by actually parsing the code, or by just going through all the lines of the program looking for what "looks like" a comment. This is so that different implementations can choose what's best for them, depending on whether they are already parsing the code or not.
To …

Define how to extract the `sourceMappingURL` comment

---

CONTRIBUTING.md
PROCESS.md

We've been having a bit of discussion at the hackathon and I'd like to be more transparent with our thinking. We've been looking at the [scopes proposal](https://github.com/tc39/source-map/blob/main/proposals/scopes.md) and as it nears completion, it will be our first proposal to go through our [process](https://github.com/tc39/source-map/edit/main/PROCESS.md). A few things occurred to us:
1. We should really try to establish a closer relationship with more stack trace rewriters. @nicolo-ribaudo said he would reach out to some folks and see if they've had any chance to look at our proposal yet.
2. Our "constituencies" language of "generators", "debuggers" and "Error monitoring tools" is proving a bit difficult to work with. There will surely be proposals like "custom formatters" that will …

Change our process to group stack trace rewriters and debuggers

---

source-map.bs

This PR addresses issue #80. I'm adding it here to have for discussion when we go through all the spec issues in the hackfest.

Add language clarifying the 32-bit limit for VLQs

---

source-map.bs

The old URL serves 404 Error now.

 Fix "This version" URL pointing to former source-map org

---

proposals/scopes.md

This changes the order of binding expressions to use encode `M` first. If `M` is >= -1, then `M` is treated as an offset into `names` for the entirety of the generated range. If it's negative, then there are `-M` sub-ranges for this variable within the generated range, and the next VLQ is the offset into `names` to use for the start of the generated range.

Scopes: Update `binding` expression parsing

---

source-map.bs

@nicolo-ribaudo @takikawa and I took an initial pass at reading and making changes to the spec. Just trying to make it easier to read. I still want to go through the second half but these seemed like nice changes.

First pass at spec review

---

proposals/scopes.md

This changes `kind` from an enum of known values, to be an index into the `names` field holding any arbitrary string. This allows us to better accommodate non-JS languages.

Scopes: Update `kind` to be an arbitrary string in the `names` field

---

proposals/scopes.md

I noticed that the main example in the scopes proposal document seems to be out-of-date with the current data representation/encoding details. This PR is an attempt to update it.
I'd appreciate any feedback on the content because I'm not sure if I've used the fields in the intended way or if the scopes look quite right.

Update the scopes proposal example for recent changes

---

source-map.bs

This PR adds some examples to the spec document for VLQ encoding.

Add examples for Base64 VLQ encoding

---

source-map.bs

This PR introduces "decoded source map" data structures, which are
internal spec representations of the information encoded in source maps.
It also defines algorithms to decode source maps from either a JSON
string or [infra](https://infra.spec.whatwg.org/) representation.
The goal is:
- use them to explicitly write down all the possible error cases
- use them as a starting point to define new data structures, for
example for the scopes proposal
- eventually add algorithms such as "get the original location given a
decoded source map and a generated location".
This PR also explicitly defines sources/sourceRoot resolution in terms
of the [WHATWG URL](https://url.spec.whatwg.org/) spec.
There are a few points where I'm not sure about what the current/expected behavior is; I marked them with …

Define decoding algorithms for source maps

---

source-map.bs

This PR is a initial take to at least clarify on a very basic level where we allow mappings for JavaScript. The current draft proposes to use "input elements" instead of "ECMAScript tokens" since generators might want to map comments as well (e.g. a TypeScript -> JavaScript with JSDoc transformer that maps the `@param` back to the TS type annotation).
The main reasoning behind the current draft is that it seldom make sense to have mappings in the middle of tokens. E.g. with `let foo = 5;`, you don't really need a mapping for the `o` in `foo`. The exception (I think) are string literals where minifiers could combine multiline string literals into a single literal. Template literals might also fall under this category so we could move them down to the second bullet point.
I don't see a use …

[mappings] Define for each ECMAScript input element where mappings are allowed

---

source-map.bs

This PR shouldn't make any semantic changes and should be purely editorial. It adjusts markup and rewords prose for consistency, clarity, or more spec-like wording. (the commit message has more details)
It builds on PR #126 so should be rebased & merged after that.

Editorial: various edits for style and clarity

---

source-map.bs

A small refactoring so the scopes proposal can re-use the same logic to validate `originalScopes` and `generatedRanges`.

Editorial: Extract 'validate base64 VLQ groupings' algorithm

---

source-map.bs

This is a minor editorial PR that fixes most of the bikeshed warnings and adjusts linking (in particular, makes sure "map" links to the infra spec where appropriate).
There are just two warnings left after this PR:
```
LINE 683: Unexported dfn that's not referenced locally - did you mean to export it?
<dfn bs-line-number="683" data-dfn-for="index-map" data-dfn-type="dfn" id="index-map-offset" data-lt="offset" data-noexport="by-default" class="dfn-paneled"><code bs-line-number="683" class="highlight">offset</code></dfn>
LINE 687: Unexported dfn that's not referenced locally - did you mean to export it?
<dfn bs-line-number="687" data-dfn-for="index-map" data-dfn-type="dfn" id="index-map-map" data-lt="map" data-noexport="by-default" class="dfn-paneled"><code bs-line-number="687" …
```

Editorial: fixes to suppress bikeshed warnings

---

source-map.bs

It was pointed out during the October 2024 plenary that being able to cause a tool to perform a network request can be used for tracking purposes, and thus it should be possible to statically know whether a file links to a source map or not.
The problem is that, given that we have multiple linking methods _that give different results_, it's not unlikely that ambiguous source map comments can skip through reviews and checks.
There was a solution that we collectively came up with, but we did not want to change the specification at this point given that we need to discuss it in TG4 and go through the implications of it.
Approval on publishing the first edition of our spec was conditional of explicitly calling out (in a note / not normative section) the implications of the ambiguity, and how …

Add security warning for ambiguous source maps

---

proposals/scopes.md

This PR is the result of presenting the ["Scopes - missing bits" slides](https://docs.google.com/presentation/d/1MUQ1F_KxrWRNReOhIKhSV7QYYNo6eqrxk1oP72MSrv0/edit?usp=sharing) to TG4 and incorporating the feedback and follow-up discussion.
Specifically this PR changes the following:
- Make `OriginalScope.kind` optional. The free-form text can't really be used by consumers in algorithms that apply the scopes info to stack traces. As such it serves mostly as a user-facing label in debuggers/stack trace processors.
- Add `OriginalScope.isStackFrame` and `GeneratedRange.isStackFrame` to signify whether a scope/range corresponds to the semantic equivalent of a function call in the authored/generated language respectively. For `GeneratedRange.isStackFrame` we re-use the existing …

Scopes: Add isStackFrame/isHidden bits and make 'kind' optional

---

proposals/debug-id.md

Simply formats the Debug ID proposal by putting sentences into individual lines to make the document less cumbersome to edit and to better be able to track changes.

Debug IDs: Format proposal text

---

source-map.bs

This PR fixes an issue identified in the tests repo (https://github.com/tc39/source-map-tests/issues/25) for a small bug in name index range checking in the spec algorithm. It should check "greater than or equal to" (as done for `sourceIndex`) instead of "greater than".

Use "greater than or equal to" for nameIndex

---

source-map.bs

We missed this when doing https://github.com/tc39/source-map/pull/140.

Last piece of ExeCom feedback

---

proposals/debug-id.md

Based on: https://github.com/tc39/source-map/pull/141
--- 
- Clarify how Debug IDs should be generated and explain proposed requirement of 128 bit UUID.
- Clarify that Debug IDs do not need to be deterministic and why they don't need to be deterministic.

Debug IDs: Clarify how Debug IDs should be generated

---

proposals/debug-id.md

Builds on https://github.com/tc39/source-map/pull/141
---
This proposal change may be a bit controversial.
I am suggesting to limit Debug IDs within Source Maps and generated files to be in a specific format - specifically the canonical UUID format (e.g. `85314830-023f-4cf1-a267-535f4e37bb17`)
This is for the very simple reason of ensuring compatibility, consistency and simplicity in the ecosystem.
Drawbacks are:
- Reduced flexibility
- 4 more bytes per file
Would be great to have some feedback and discussions around this!

Debug IDs: Only allow Debug IDs in the canonical UUID format

---

proposals/debug-id.md

Builds on https://github.com/tc39/source-map/pull/141
--- 
Replaces the "Emulating Debug IDs" section with a more concrete polyfilling section the tech of which is already used in production systems.
Also demotes the "Parsing Debug IDs" section to a "Questions" section because it still seems unclear what the `//# sourceMappingURL` comment spec will evolve to and we likely want to very closely follow that spec for Debug IDs.

Debug IDs: Add "Polyfills" and remove "Parsing" section

---

source-map.bs

This PR unifies ECMA-262 references in the spec to match the PDF version and reduce redundancy.

Editorial: unify ECMA-262 references

---

source-map.bs

Right now the draft PDF spec (in ECMA format) and the web spec don't align on the numbered bullet styles in algorithms. This PR changes the web version to match using CSS.
This also changes numbered bullets that aren't in algorithms, such as those in "5.1.2. Names for generated JavaScript code" (which is not in the 2024 branch) because we don't have a CSS class to distinguish them. I think in that particular case, we could just use unordered lists instead if we don't like the alternating bullets.

Editorial: Add CSS to adjust list bullets to match ECMA

---

proposals/debug-id.md

Adds a section with a complete list of current implementors and implementations that are work-in-progress.

Debug IDs: Add implementors section

---

README.md
proposals/debug-id.md

In the last TG4 monthly meeting we decided to advance the Debug ID proposal to stage 2 given the proposal is written out in detail and also has some adoption.
I am happy to wait a few more weeks to give people the opportunity to object.

Advance Debug ID proposal to stage 2

---

source-map.bs

This was suggested on Matrix by other delegates with more Ecma experience than us, highlighting that the work Jon and I have been doing in the past months to get the spec to a good Ecma state is similar to an editor's role, even without being officially editors.
I copied the way of listing editor names from ECMA-262 and ECMA-402 (as "signatures" at the end of the introduction).

Add aknowledgment for editorial changes in first Ecma edition

---

.github/workflows/ipr.yml

CI will fail in this PR, because it runs from `main`. We need to merge to actually make it work.

Fix IPR check after repo rename

---

source-map.bs

This PR has additional editorial changes needed to make the web spec consistent with the 2024 PDF.
* Use consistent casing throughout (e.g., sections, titles)
* Must -> shall
* Move some references to bibliography section, adjust references section to match PDF
* Adjust boilerplate to ensure section ordering at end (index, bibliography, license) matches PDF
* Add JSON normative ref
Possible additional TODO:
* Should we have an "Annex A" heading in the web version too?
* Keep the issues list or remove it?
* Formatting of individual references in bibliography/normative refs

Editorial: more changes to conform with ECMA format

---

.github/workflows/auto-publish.yml

This CL changes the auto publish workflow to build all branches (except `gh-pages`) and put the result into `<branch name>/index.html` on the `gh-pages` branch. The `main` branch is still published to the root `index.html` though.
This is very convenient for forks, since it's straight-forward to preview PRs.

Workflow: Auto-publish all branches to gh-pages

---

README.md

Also mention that we have an actual spec, and not just a "work in progress" :) (even though it will only be approved later this week)

Update readme after rename and license change

---

source-map.bs

Unfortunately Bikeshed doesn't have a more suitable marker that we can use in TC39. We can iterate on it while migrating to Ecmarkup :)

Mark as "Stage 4"

---

source-map.bs

[**Rendered draft**](https://takikawa.github.io/source-map-spec/#decoding-an-index-map)
This PR adds a decoding algorithm for index maps along the lines of the existing algorithms for normal source maps.
I'll leave a few comments for cases in the spec where it's not clear what we should do:
* Error cases for offsets
* The check for index map overlap

Add a decoding algorithm for index maps

---

spec.emu

Fixes https://github.com/tc39/ecma426/issues/178
~~Preview: https://tc39.es/ecma426/pr/179/#sec-DecodeBase64VLQ~~
**Edit**: The preview script is broken. Actual preview at https://nicolo-ribaudo.github.io/source-map/branch/issue-178/#sec-DecodeBase64VLQ

Fix masking of continuation bit in DecodeBase64VLQ

---

proposals/scopes.md

This PR applies the changes to "decoding state" as discussed in the meeting of 2025-03-27:
* `original_scope_start` and `original_scope_end` column is relative if the previous item was on the same line.
* We now reset only line/column across source files. "name", "kind" and "variables" stay relative.
* `generated_range_callsite` now uses absolute unsigned values, as we don't know if there is an actual benefit to encoding callsites relative.
Once this PR and #187 have landed, I'll update https://jsr.io/@chrome-devtools/source-map-scopes-codec to reflect the changes.

Scopes: Use relative encoding for column, absolute for callsite

---

spec.emu

Draft that changes VLQ and mappings to use grammar plus "syntax-directed operations" for decoding rather than a pure algorithmic approach.
Only uploaded so we have a preview for discussion.
Preview: https://szuend.github.io/source-map/branch/mappings-grammar/#sec-mappings

Editorial: Use grammar for VLQ and Mappings and decode via SDO

---

.github/workflows/auto-publish.yml

See https://github.com/tc39/ecma426/pull/189, tested at https://github.com/nicolo-ribaudo/source-map/pull/2.
The problem was that we were linting on the `main` spec.emu, rather than the PR, because we are running on `pull_request_target`. This change gets the spec files from the PR, so that we are actually linting them.

Fix CI linting

---

package.json
scripts/ecmarkup.js
spec.emu

Ecmarkup supports linting, to enforce a consistent style and to prevent simple bugs (e.g. using undeclared variables). We didn't originally enable it, because of many false positives about completion records (which we do not use).
This PR patches ecmarkup to suppress false positives, enables linting, and fixes all the valid linting issues.

Support linting the spec

---

spec.emu

Now that ecmarkup supports dark mode, the emu-notes cause a bit of a readability issue (in that they're impossible to read) as they set light backgrounds which contrast poorly with the page-wide foreground color. Setting the foreground color to black for both seems appropriate.
Image, for reference:
> https://tc39.es/ecma426/#sec-linking-inline
The hljs setup will need to be adjusted yet too, though that can be done separately by someone else. Seems a bit more involved and would need some playing with, whilst this is just a drive-by fix.

fix: Improve 'emu-note' text contrast w/ dark mode

---

spec.emu

This matches impl behavior for `sourceRoot`. If set, it's treated as a path, and if it does not end with a `/`, it is appended with one:
- [Chrome](https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/core/sdk/SourceMap.ts;l=486-492;drc=6ca4ad9f4aac1de91c8b5095b8fdb558ad9e7c5e)
- [Mozilla](https://github.com/mozilla/source-map/blob/3cb92cc3b73bfab27c146bae4ef2bc09dbb4e5ed/lib/util.js#L440)
- [trace-mapping](https://github.com/jridgewell/trace-mapping/blob/5a658b10d9b6dea9c614ff545ca9c4df895fee9e/src/resolve.ts#L10-L13)
I think the confusion here came from `baseURL` (the map file's URL), which **is** filename trimmed.

Fix sourceRoot decoding

---

spec.emu

This PR adds the 'Position' record consisting of a line plus column and a 'Original Position' record, consisting of a source index, line and column.
The mapping record thus changes to contain one generated position record and one original position record. This makes the intention of a mapping a bit more clear in the spec: e.g. a [[OriginalLine]] that is null while [[OriginalColumn]] is present, does not make a lot of sense (while possible to achieve in the encoding).
The PR also provides a general comparison function and replaces the adhoc "LessThan" mapping comparison in the index decoding algorithm.
We'll also use the 'Position' record in the spec text of the "scopes" proposal.
Preview: https://tc39.es/ecma426/pr/194/

Editorial: Add 'Position' and 'Original Position' records

---

proposals/debug-id.md

- No longer suggest a JS API in the main part of the proposal (we still discuss possible options in an appendix to highlight the value for post-hoc debugging)
- Be more specific about JS APIs (ref https://github.com/tc39/ecma426/issues/146)
- Remove unnecessary details from symbol server section (we don't care about the storage mechanism)
cc @szuend

Move JS API out of debug ID proposal

---

proposals/debug-id.md

I stumbled on another use case by browsing through some issues:
- https://github.com/tc39/ecma426/issues/14
- https://github.com/tc39/ecma426/issues/182#issuecomment-2821067733

Debug ID proposal: Add benefit of being able to link additional information to source maps

---

proposals/scopes.md

As discussed in the meeting of 2025-04-24, this PR changes the binding expressions from a signed VLQ to a unsigned VLQ. To signify a variable is unavailable in a given generated (sub) range, we use `0` instead of `-1` and the indices themselves are now 1-based instead of 0-based. This is necessary to free up `0` as the "unavailability marker".
To capture some of the points of the meeting here (also available in the notes):
- Using relative indicies into the `names` array would require us to sacrifice an additional bit to signify "unavailability".
- Another option would be to use `0` as the marker and make positive relative indices "off by one". E.g. "0" means a variable is unavailable, "1" means a variable uses the same binding expression as the previous variable and "2" means it uses the …

Scopes: Use unsigned VLQ (1-based) for binding expressions

---

spec.emu

This is a minor fix for a typo in the mappings decoding algorithm.

Spec: Fix bounds check on names field decoding

---

spec.emu

* Fix JSON format in example
* Fix typo with extraneous "|"

Editorial: Minor syntactic fixes

---

spec.emu

Editorial: use 0b for binary representation

---

spec.emu

Originally opened at https://github.com/szuend/source-map/pull/1. See https://github.com/tc39/ecma426/pull/196#issuecomment-3211293112.
I tried to make it a bit easier to see what is going on by:
- giving different names to the different SDOs that take care of parsing different data about the scopes
- getting all the data and then creating the Original Scope Record, rather than creating an Original Scope Record and then mutating it
- centralizing the "increment the index in the state and get the result" in a single AO
We could do something similar for TopLevelItemList.

Scopes: Refactor scopes tree decoding

---

spec.emu

This PR adds a "VendorExtensionItem" as discussed in the TG4 meeting of 2025-08-28.
The "VendorExtensionItem" uses the tag `/` followed by a Vlq that must be interpreted as an unsigned absolute index into "names" to identify the extension.
"UnknownItem" is renamed to "InvalidItem" to better convey that generators must not emit it at this point while decoders must decode and ignore it.

Scopes: Split UnknownItem into VendorExtensionItem and InvalidItem
